import CoreData
import Foundation

// The CDChore / CDArea / CDCompletion / CDLockedDay / CDHousehold classes are
// generated by Xcode from Choreganize.xcdatamodeld (Codegen = Class Definition).
// These extensions add factories, enum bridges, and ordered accessors. Keeping
// logic in extensions avoids redeclaration clashes with the generated classes.

// MARK: - CDChore

extension CDChore {
    @discardableResult
    static func make(
        in ctx: NSManagedObjectContext,
        id: UUID = UUID(),
        name: String,
        isDaily: Bool = false,
        frequency: Frequency? = nil,
        assignedDay: Weekday? = nil,
        createdDate: Date = Date(),
        household: CDHousehold? = nil
    ) -> CDChore {
        let chore = CDChore(context: ctx)
        chore.id = id
        chore.name = name
        chore.isDaily = isDaily
        chore.frequency = frequency?.rawValue
        chore.assignedDay = assignedDay?.rawValue
        chore.createdDate = createdDate
        chore.household = household
        return chore
    }

    /// Strongly-typed bridge over the String-backed `frequency` attribute.
    var frequencyValue: Frequency? {
        get { frequency.flatMap(Frequency.init(rawValue:)) }
        set { frequency = newValue?.rawValue }
    }

    /// Strongly-typed bridge over the String-backed `assignedDay` attribute.
    var assignedDayValue: Weekday? {
        get { assignedDay.flatMap(Weekday.init(rawValue:)) }
        set { assignedDay = newValue?.rawValue }
    }

    /// CG-18 / #100 — bridge over the comma-joined `assignedDays` attribute
    /// (multi-day recurrence). Serialized in Sunday→Saturday order so the
    /// stored string is deterministic; a non-empty set supersedes the legacy
    /// single `assignedDay` in scheduling.
    var assignedDaysValue: Set<Weekday> {
        get {
            guard let assignedDays, !assignedDays.isEmpty else { return [] }
            return Set(assignedDays.split(separator: ",").compactMap { Weekday(rawValue: String($0)) })
        }
        set {
            let ordered = Weekday.standardCases.filter { newValue.contains($0) }
            assignedDays = ordered.isEmpty ? nil : ordered.map(\.rawValue).joined(separator: ",")
        }
    }

    /// CG-18 / #100 — bridge over the Int16 `recurrenceInterval` scalar. Legacy
    /// records synced in before the attribute existed read 0; both 0 and 1 mean
    /// "every period".
    var recurrenceIntervalValue: Int {
        get { max(1, Int(recurrenceInterval)) }
        set { recurrenceInterval = Int16(max(1, min(newValue, Int(Int16.max)))) }
    }

    /// CG-17 / #99 — whether the chore is assigned to the signed-in member
    /// (`assignee` and `CompleterIdentity` share the CloudKit user-record-name
    /// identity domain).
    var isAssignedToCurrentUser: Bool {
        guard let assignee else { return false }
        return assignee == CompleterIdentity.cachedID
    }

    /// Completions for this chore, newest first.
    var completionsArray: [CDCompletion] {
        (completions as? Set<CDCompletion> ?? [])
            .sorted { ($0.date ?? .distantPast) > ($1.date ?? .distantPast) }
    }
}

// MARK: - CDArea

extension CDArea {
    @discardableResult
    static func make(
        in ctx: NSManagedObjectContext,
        id: UUID = UUID(),
        name: String,
        detail: String = "",
        household: CDHousehold? = nil
    ) -> CDArea {
        let area = CDArea(context: ctx)
        area.id = id
        area.name = name
        area.detail = detail
        area.household = household
        return area
    }

    /// Chores assigned to this area, by name.
    var choresArray: [CDChore] {
        (chores as? Set<CDChore> ?? [])
            .sorted { ($0.name ?? "") < ($1.name ?? "") }
    }
}

// MARK: - CDCompletion

extension CDCompletion {
    @discardableResult
    static func make(
        in ctx: NSManagedObjectContext,
        id: UUID = UUID(),
        date: Date,
        notes: String? = nil,
        completedBy: String? = nil,
        chore: CDChore? = nil,
        household: CDHousehold? = nil
    ) -> CDCompletion {
        let completion = CDCompletion(context: ctx)
        completion.id = id
        completion.date = date
        completion.notes = notes
        completion.completedBy = completedBy
        completion.chore = chore
        completion.household = household
        return completion
    }
}

// MARK: - CDLockedDay

extension CDLockedDay {
    @discardableResult
    static func make(
        in ctx: NSManagedObjectContext,
        id: UUID = UUID(),
        date: Date,
        household: CDHousehold? = nil
    ) -> CDLockedDay {
        let locked = CDLockedDay(context: ctx)
        locked.id = id
        locked.date = date
        locked.household = household
        return locked
    }
}
